
'use server';
/**
 * @fileOverview A simple conversational AI flow using Genkit and Gemini.
 *
 * - chatWithAI - A function that takes user input and returns an AI response.
 * - ChatInput - The input type for the chatWithAI function.
 * - ChatOutput - The return type for the chatWithAI function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const ChatInputSchema = z.object({
  userMessage: z.string().describe('The message sent by the user.'),
});
export type ChatInput = z.infer<typeof ChatInputSchema>;

const ChatOutputSchema = z.object({
  aiResponse: z.string().describe('The response generated by the AI.'),
});
export type ChatOutput = z.infer<typeof ChatOutputSchema>;

export async function chatWithAI(input: ChatInput): Promise<ChatOutput> {
  return chatFlow(input);
}

const prompt = ai.definePrompt({
  name: 'chatPrompt',
  input: {
    schema: ChatInputSchema,
  },
  output: {
    schema: ChatOutputSchema,
  },
  prompt: `You are a helpful conversational AI assistant integrated into a video chat application. Respond concisely and helpfully to the user's message.

User Message: {{{userMessage}}}

Your Response:`,
});

const chatFlow = ai.defineFlow<
  typeof ChatInputSchema,
  typeof ChatOutputSchema
>(
  {
    name: 'chatFlow',
    inputSchema: ChatInputSchema,
    outputSchema: ChatOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    // Ensure output is not null or undefined before returning
    if (!output) {
        throw new Error("AI did not return a valid response.");
    }
    return output;
  }
);
